# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(756, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 80, 661, 441))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txt = QtWidgets.QLineEdit(self.frame)
        self.txt.setMinimumSize(QtCore.QSize(0, 28))
        self.txt.setAlignment(QtCore.Qt.AlignCenter)
        self.txt.setObjectName("txt")
        self.horizontalLayout.addWidget(self.txt)
        self.btn_open = QtWidgets.QPushButton(self.frame)
        self.btn_open.setMinimumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_open.setFont(font)
        self.btn_open.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_open.setStyleSheet("QPushButton{bordert-top-right-radious: 15px; background-color: rgb(255, 255, 0)}\n"
"QPushButton:hover{color: #000000; background-color: rgb(0, 255, 255)}\n"
"")
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.btn_organize = QtWidgets.QPushButton(self.frame)
        self.btn_organize.setMinimumSize(QtCore.QSize(200, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_organize.setFont(font)
        self.btn_organize.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btn_organize.setStyleSheet("QPushButton{bordert-top-right-radious: 15px;background-color: rgb(255, 255, 0)}\n"
"QPushButton:hover{color: #000000; background-color: rgb(0, 255, 255)}\n"
"")
        self.btn_organize.setObjectName("btn_organize")
        self.horizontalLayout_2.addWidget(self.btn_organize)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\"C:\\Users\\Pedro\\Desktop\\CYBER TECH\\logo_cyber_tech.png\" alt=\"Marca Cyber Tech\"></p><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">File Organizer</span></p></body></html>"))
        self.txt.setPlaceholderText(_translate("MainWindow", "selecione a pasta"))
        self.btn_open.setText(_translate("MainWindow", "Open File"))
        self.btn_organize.setText(_translate("MainWindow", "Organize"))

